### PR TITLE
Permissions

### PR DESCRIPTION
**Pull request by harisibrahimkv**

### CODE REVIEW

**Comment by harisibrahimkv** [comment]
@subhaklp @meghaklp Okay so I think we are in a good spot to roll this out.

I'll just run you through what the logic is over here and let's have a quick review before I merge this in.

By default, all endpoints (except the ones that we'll list shortly) are allowed the following permissions:

1. (u'GET', u'HEAD', u'OPTIONS')
2. If the user is superuser
3. If the user belongs to the `tada_admin` group.

Now, the following entities have specific permissions apart from the ones above. Meaning if any of the above is true, the following entities will work fine on their respective endpoints. If all three above are false, then the specific permissions (as listed below for each), are checked.

1. Institution.
 * For PATCH, PUT and DELETE:
  - Allowed if the user has `change_institution` permission on the specific `institution` object.
 * For POST:
  - Allowed if the user has `add_institution` permission on the `boundary` under which this is going to be created.

2. StudentGroup, Staff and Student.
 - Action is allowed if the user has `crud_student_class_staff` permission on the `institution` under which this is going to be created.

3. Assessments
 * This is only going to come into picture when we start working with the answers endpoint.

## Who can assign permissions?
1. A superuser
2. A person belonging to the `tada_admin` group.
3. A person belonging to the `tada_dee` group.

## How can I assign permissions?
```
curl -H "Content-Type:application/json" -H "Authorization: Token ee71aefc7dd21a3e6e88e0142b1da6a0db298cf8" -X POST -d '{"boundary_id":xxxx, "institution_id":xxxx, "assessment_id":xxxx}' 'http://localhost:8000/auth/users/288/permissions/'
```

## What happens when I assign permissions?

 * Permissions are assigned to the user whose ID is defined in the URL. So in the example, that would be user id 288.

1. If you specify an `institution_id`:
 - A `change_institution` permission will be assigned to that user on that `institution`.
 - A `crud_student_class_staff` permission will be assigned to that user on that `institution`.
 
2. If you specify a `boundary_id`:
 - All the above happens for each `institution` under that `boundary`.
 - A `add_institution` permission will be assigned to that user on all the `clusters` coming under that `boundary`. If the `boundary_id` is that of a cluster, then only that cluster.

3. If you specify a 'assessment_id`:
 - A `change_assessment` permission is assigned to that user on that `assessment`. However, this is only coming into picture when we work with answers.

## How can I unassign permissions?
 ```
curl -H "Content-Type:application/json" -H "Authorization: Token ee71aefc7dd21a3e6e88e0142b1da6a0db298cf8" -X DELETE -d '{"boundary_id":xxxx, "institution_id":xxxx, "assessment_id":xxxx}' 'http://localhost:8000/auth/users/288/permissions/'
```

## What happens when I unassign permissions?
 - Exactly the opposite of what happens when you assign permissions, which is detailed above.

## Additional info about this pull request
 * All /auth/users/ endpoint actions will be reserved for `superuser`s and `tada_admin`s once this is merged.
 * However, we specifically allow a `user` to work on their own object. Meaning a `user` can edit their own `first_name`, `last_name`, `password`, etc. But no one else's.
 * Enforces the "One group per person" .
 * Overrides the `/login/` endpoint to return the `user_id` in the response as well:

```
curl -X POST http://localhost:8000/auth/login/ --data 'username=dummy@gmail.com&password=123'
```

```json
{"auth_token":"6e025a5dc6ab2f990c854e8856dc484e0b15b403","user_id":291}
```

 * Casts the `superuser` role as the `tada_admin` role while serializing the `groups` to which a `user` belongs to.

 * Returns all available permissions for a user on the `/users/id` endpoint. Following is an example JSON being returned:

```
curl -H "Content-Type:application/json" -H "Authorization: Token 6e025a5dc6ab2f990c854e8856dc484e0b15b403" -X GET "http://localhost:8000/auth/users/291/" 
```

```json
{
    "email": "",
    "first_name": "",
    "groups": [],
    "id": 291,
    "last_name": "",
    "permissions": {
        "assessments": [],
        "boundaries": [
            9051
        ],
        "institutions": [
            35801,
            35802,
            35803,
            35804,
            35805,
            35806,
            35807,
            35808,
            35809,
            35810,
            35811,
            35812,
            35813,
            35814,
            35815,
            35816,
            35817,
            35818,
            35819,
            35820,
            35821,
            35822,
            35823,
            35824
        ]
    },
    "username": "dummy@gmail.com"
}
```

## Things that still need work
 - [ ] DEEs can assign permissions. The document says we should only allow them to assign permissions to boundaries and entities under which they have permissions to. Is that a requirement in a real life use case?
 - [x] ~Need to modify the `/me` endpoint to return all the permissions details on it.~ Implements this on the `/users/id` endpoint. 

## What does this all mean??
 - Time to take on the world. Let's go!

**Comment by harisibrahimkv** [comment]
Decided to not make the permissions too granular. Working on the permissions simply being implemented at the cluster and institution levels.

**Comment by subhaklp** [comment]
@harisibrahimkv is a superuser different from a tada_admin user?? What's the difference?

**Comment by subhaklp** [comment]
@harisibrahimkv @meghaklp if a person has a "add_institution" permission, wouldn't that mean he also has add_studentgroup, add_students etc..? 

@subhaklp - as per the new design if a person has add_institution on institution_id they have CRUD access to all entities under it - with crud_student_class_staff

**Comment by subhaklp** [comment]
Also @harisibrahimkv  if you can paste a sample JSON response for each call, that'd help very much for the frontend? i.e. when a user logs in, what' the JSON expected that details permissions?

**Comment by harisibrahimkv** [comment]
@subhaklp superuser is the django default superuser role. It has nothing to do with Tada as such. In the context of Tada, the `tada_admin` is the superuser.

```
if a person has a "add_institution" permission, wouldn't that mean he also has add_studentgroup, add_students etc..?
```

Yes. That is what I've mentioned on point 2 under "What happens when I assign permissions". But anyway, there is a slight change to how this is implemented on the backend which I am working on now.

The /permissions/ endpoint just returns `permissions assigned` or `permissions unassigned` right now. I'll have to modify the `/me` endpoint to return all the permissions that a user has.

**Pull request merged**
